name: Update UPDATES with Current Date

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  update-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update updates
        run: |
          current_date=$(TZ=Europe/Helsinki date +'%B %d, %Y')
          current_time=$(TZ=Europe/Helsinki date +'%H:%M:%S')
          commit_name=$(git log --format='%an' -n 1 $GITHUB_SHA)
          commit_message=$(git log --format=%B -n 1 $GITHUB_SHA)
          echo -e "## Chatty-Bot commits\n- Date: $current_date\n- Time: $current_time GMT+2\n- Commit Name: $commit_message\n- Committed by: $commit_name\n\n$(cat updates.md)" > updates.md
          git add updates.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update updates.md with Chatty-Bot commit log" || exit 0
          git push
